import { Meta, StoryObj } from '@storybook/react';
import { CopyButton } from './CopyButton';
declare const meta: Meta<typeof CopyButton>;
export default meta;
type Story = StoryObj<typeof CopyButton>;
export declare const Default: Story;
export declare const IconOnly: Story;
export declare const Variants: Story;
export declare const VariantsIconOnly: Story;
export declare const Sizes: Story;
export declare const SizesIconOnly: Story;
export declare const CustomIcons: Story;
export declare const CustomLabels: Story;
export declare const Disabled: Story;
export declare const WithCallback: Story;
export declare const CopyableDefault: Story;
export declare const CopyableTruncated: Story;
export declare const CopyableExamples: Story;
export declare const InlineUsage: Story;
export declare const CodeBlock: Story;
export declare const TableCell: Story;
