import { Meta, StoryObj } from '@storybook/react-vite';
import { Toggle } from './Toggle';
declare const meta: Meta<typeof Toggle>;
export default meta;
type Story = StoryObj<typeof Toggle>;
export declare const Default: Story;
export declare const Checked: Story;
export declare const WithDescription: Story;
export declare const WithoutLabel: Story;
export declare const Disabled: Story;
export declare const Controlled: Story;
export declare const SettingsExample: Story;
export declare const AllStates: Story;
