import { Meta, StoryObj } from '@storybook/react-vite';
import { DetailHeader } from './DetailHeader';
declare const meta: Meta<typeof DetailHeader>;
export default meta;
type Story = StoryObj<typeof DetailHeader>;
export declare const Default: Story;
export declare const WithCopyable: Story;
export declare const WithStatus: Story;
export declare const WithCustomValue: Story;
export declare const VMDetail: Story;
export declare const ServiceDetail: Story;
export declare const WithInfoCardTooltip: Story;
export declare const Minimal: Story;
