import { Meta, StoryObj } from '@storybook/react-vite';
import { Tabs } from './Tabs';
declare const meta: Meta<typeof Tabs>;
export default meta;
type Story = StoryObj<typeof Tabs>;
export declare const Default: Story;
export declare const Boxed: Story;
export declare const Controlled: Story;
export declare const WithDisabledTab: Story;
export declare const Sizes: Story;
export declare const WithBadges: Story;
export declare const SettingsPage: Story;
export declare const BoxedToggle: Story;
