import { Meta, StoryObj } from '@storybook/react-vite';
import { Toast } from './Toast';
declare const meta: Meta<typeof Toast>;
export default meta;
type Story = StoryObj<typeof Toast>;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const Info: Story;
export declare const WithTitle: Story;
export declare const WithProject: Story;
export declare const WithLink: Story;
export declare const WithAction: Story;
export declare const WithDetail: Story;
export declare const NonDismissible: Story;
export declare const AllVariants: Story;
export declare const Interactive: Story;
