import { Meta, StoryObj } from '@storybook/react-vite';
import { TopBar } from './TopBar';
declare const meta: Meta<typeof TopBar>;
export default meta;
type Story = StoryObj<typeof TopBar>;
export declare const Default: Story;
export declare const WithSidebarToggle: Story;
export declare const WithNotificationBadge: Story;
export declare const WithoutNavigation: Story;
export declare const DisabledNavigation: Story;
export declare const Minimal: Story;
export declare const FullFeatured: Story;
