/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './thaki-shared-v2/src/components/**/*.{ts,tsx}',
    './thaki-shared-v2/src/components/**/*.{js,jsx}',
  ],
  safelist: [
    'h-control-sm', 'h-control-md', 'h-control-lg',
    'min-h-control-sm', 'min-h-control-md', 'min-h-control-lg',
    'px-control-x-sm', 'px-control-x-md', 'px-control-x-lg',
    'py-control-y-sm', 'py-control-y-md', 'py-control-y-lg',
    'duration-normal', 'duration-fast', 'duration-slow',
    'ease-in-out', 'ease-out',
  ],
  darkMode: ['variant', '&:is(.dark *):not([data-theme="light"] *)'],
  theme: {
    extend: {
      colors: {
        'primary': 'var(--semantic-color-primary)',
        'primary-hover': 'var(--semantic-color-primary-hover)',
        'primary-focus': 'var(--semantic-color-primary-focus)',
        'on-primary': 'var(--semantic-color-on-primary)',
        'secondary': 'var(--semantic-color-secondary)',
        'secondary-hover': 'var(--semantic-color-secondary-hover)',
        'secondary-focus': 'var(--semantic-color-secondary-focus)',
        'on-secondary': 'var(--semantic-color-on-secondary)',
        'tertiary': 'var(--semantic-color-tertiary)',
        'tertiary-hover': 'var(--semantic-color-tertiary-hover)',
        'tertiary-focus': 'var(--semantic-color-tertiary-focus)',
        'on-tertiary': 'var(--semantic-color-on-tertiary)',
        'surface': 'var(--semantic-color-surface)',
        'surface-muted': 'var(--semantic-color-surface-muted)',
        'surface-hover': 'var(--semantic-color-surface-hover)',
        'surface-tertiary': 'var(--semantic-color-surface-tertiary)',
        'surface-elevated': 'var(--semantic-color-surface-elevated)',
        'text': 'var(--semantic-color-text)',
        'text-muted': 'var(--semantic-color-text-muted)',
        'text-subtle': 'var(--semantic-color-text-subtle)',
        'text-disabled': 'var(--semantic-color-text-disabled)',
        'text-inverse': 'var(--semantic-color-text-inverse)',
        'text-on-primary': 'var(--semantic-color-text-on-primary)',
        'border': 'var(--semantic-color-border)',
        'border-subtle': 'var(--semantic-color-border-subtle)',
        'border-strong': 'var(--semantic-color-border-strong)',
        'border-focus': 'var(--semantic-color-border-focus)',
        'state-info': 'var(--semantic-color-state-info)',
        'state-info-bg': 'var(--semantic-color-state-info-bg)',
        'state-info-text': 'var(--semantic-color-state-info-text)',
        'state-success': 'var(--semantic-color-state-success)',
        'state-success-bg': 'var(--semantic-color-state-success-bg)',
        'state-success-text': 'var(--semantic-color-state-success-text)',
        'state-warning': 'var(--semantic-color-state-warning)',
        'state-warning-bg': 'var(--semantic-color-state-warning-bg)',
        'state-warning-text': 'var(--semantic-color-state-warning-text)',
        'state-danger': 'var(--semantic-color-state-danger)',
        'state-danger-bg': 'var(--semantic-color-state-danger-bg)',
        'state-danger-text': 'var(--semantic-color-state-danger-text)',
        'primitive-white': 'var(--primitive-color-white)',
        'primitive-black': 'var(--primitive-color-black)',
        'primitive-blue-gray10': 'var(--primitive-color-blue-gray10)',
        'primitive-blue-gray50': 'var(--primitive-color-blue-gray50)',
        'primitive-blue-gray100': 'var(--primitive-color-blue-gray100)',
        'primitive-blue-gray200': 'var(--primitive-color-blue-gray200)',
        'primitive-blue-gray300': 'var(--primitive-color-blue-gray300)',
        'primitive-blue-gray400': 'var(--primitive-color-blue-gray400)',
        'primitive-blue-gray500': 'var(--primitive-color-blue-gray500)',
        'primitive-blue-gray600': 'var(--primitive-color-blue-gray600)',
        'primitive-blue-gray700': 'var(--primitive-color-blue-gray700)',
        'primitive-blue-gray800': 'var(--primitive-color-blue-gray800)',
        'primitive-blue-gray900': 'var(--primitive-color-blue-gray900)',
        'primitive-blue-gray950': 'var(--primitive-color-blue-gray950)',
        'primitive-cool-gray50': 'var(--primitive-color-cool-gray50)',
        'primitive-cool-gray100': 'var(--primitive-color-cool-gray100)',
        'primitive-cool-gray200': 'var(--primitive-color-cool-gray200)',
        'primitive-cool-gray300': 'var(--primitive-color-cool-gray300)',
        'primitive-cool-gray400': 'var(--primitive-color-cool-gray400)',
        'primitive-cool-gray500': 'var(--primitive-color-cool-gray500)',
        'primitive-cool-gray600': 'var(--primitive-color-cool-gray600)',
        'primitive-cool-gray700': 'var(--primitive-color-cool-gray700)',
        'primitive-cool-gray800': 'var(--primitive-color-cool-gray800)',
        'primitive-cool-gray900': 'var(--primitive-color-cool-gray900)',
        'primitive-blue50': 'var(--primitive-color-blue50)',
        'primitive-blue100': 'var(--primitive-color-blue100)',
        'primitive-blue200': 'var(--primitive-color-blue200)',
        'primitive-blue300': 'var(--primitive-color-blue300)',
        'primitive-blue400': 'var(--primitive-color-blue400)',
        'primitive-blue500': 'var(--primitive-color-blue500)',
        'primitive-blue600': 'var(--primitive-color-blue600)',
        'primitive-blue700': 'var(--primitive-color-blue700)',
        'primitive-blue800': 'var(--primitive-color-blue800)',
        'primitive-blue900': 'var(--primitive-color-blue900)',
        'primitive-red50': 'var(--primitive-color-red50)',
        'primitive-red100': 'var(--primitive-color-red100)',
        'primitive-red200': 'var(--primitive-color-red200)',
        'primitive-red300': 'var(--primitive-color-red300)',
        'primitive-red400': 'var(--primitive-color-red400)',
        'primitive-red500': 'var(--primitive-color-red500)',
        'primitive-red600': 'var(--primitive-color-red600)',
        'primitive-red700': 'var(--primitive-color-red700)',
        'primitive-red800': 'var(--primitive-color-red800)',
        'primitive-red900': 'var(--primitive-color-red900)',
        'primitive-green50': 'var(--primitive-color-green50)',
        'primitive-green100': 'var(--primitive-color-green100)',
        'primitive-green200': 'var(--primitive-color-green200)',
        'primitive-green300': 'var(--primitive-color-green300)',
        'primitive-green400': 'var(--primitive-color-green400)',
        'primitive-green500': 'var(--primitive-color-green500)',
        'primitive-green600': 'var(--primitive-color-green600)',
        'primitive-green700': 'var(--primitive-color-green700)',
        'primitive-green800': 'var(--primitive-color-green800)',
        'primitive-green900': 'var(--primitive-color-green900)',
        'primitive-orange50': 'var(--primitive-color-orange50)',
        'primitive-orange100': 'var(--primitive-color-orange100)',
        'primitive-orange200': 'var(--primitive-color-orange200)',
        'primitive-orange300': 'var(--primitive-color-orange300)',
        'primitive-orange400': 'var(--primitive-color-orange400)',
        'primitive-orange500': 'var(--primitive-color-orange500)',
        'primitive-orange600': 'var(--primitive-color-orange600)',
        'primitive-orange700': 'var(--primitive-color-orange700)',
        'primitive-orange800': 'var(--primitive-color-orange800)',
        'primitive-orange900': 'var(--primitive-color-orange900)',
        'primitive-yellow50': 'var(--primitive-color-yellow50)',
        'primitive-yellow100': 'var(--primitive-color-yellow100)',
        'primitive-yellow200': 'var(--primitive-color-yellow200)',
        'primitive-yellow300': 'var(--primitive-color-yellow300)',
        'primitive-yellow400': 'var(--primitive-color-yellow400)',
        'primitive-yellow500': 'var(--primitive-color-yellow500)',
        'primitive-yellow600': 'var(--primitive-color-yellow600)',
        'primitive-yellow700': 'var(--primitive-color-yellow700)',
        'primitive-yellow800': 'var(--primitive-color-yellow800)',
        'primitive-yellow900': 'var(--primitive-color-yellow900)',
      },
      spacing: {
        '0': 'var(--primitive-space-0)',
        '1': 'var(--primitive-space-1)',
        '2': 'var(--primitive-space-2)',
        '3': 'var(--primitive-space-3)',
        '4': 'var(--primitive-space-4)',
        '5': 'var(--primitive-space-5)',
        '6': 'var(--primitive-space-6)',
        '7': 'var(--primitive-space-7)',
        '8': 'var(--primitive-space-8)',
        '9': 'var(--primitive-space-9)',
        '10': 'var(--primitive-space-10)',
        '12': 'var(--primitive-space-12)',
        '14': 'var(--primitive-space-14)',
        '16': 'var(--primitive-space-16)',
        '20': 'var(--primitive-space-20)',
        '24': 'var(--primitive-space-24)',
        '32': 'var(--primitive-space-32)',
        '0.5': 'var(--primitive-space-0-5)',
        '1.5': 'var(--primitive-space-1-5)',
        '2.5': 'var(--primitive-space-2-5)',
        xs: 'var(--semantic-space-xs)',
        sm: 'var(--semantic-space-sm)',
        md: 'var(--semantic-space-md)',
        lg: 'var(--semantic-space-lg)',
        xl: 'var(--semantic-space-xl)',
        '2xl': 'var(--semantic-space-2xl)',
        '3xl': 'var(--semantic-space-3xl)',
        inline: 'var(--semantic-space-inline)',
        stack: 'var(--semantic-space-stack)',
        inset: 'var(--semantic-space-inset)',
        section: 'var(--semantic-space-section)',
        block: 'var(--semantic-space-block)',
      },
      borderRadius: {
        none: 'var(--semantic-radius-none)',
        sm: 'var(--semantic-radius-sm)',
        base: 'var(--semantic-radius-base)',
        md: 'var(--semantic-radius-md)',
        lg: 'var(--semantic-radius-lg)',
        xl: 'var(--semantic-radius-xl)',
        full: 'var(--semantic-radius-full)',
        control: 'var(--semantic-radius-control)',
        card: 'var(--semantic-radius-card)',
        modal: 'var(--semantic-radius-modal)',
        base4: 'var(--semantic-radius-base4)',
        base6: 'var(--semantic-radius-base6)',
        base8: 'var(--semantic-radius-base8)',
        base16: 'var(--semantic-radius-base16)',
      },
      height: {
        'control-sm': 'var(--semantic-control-height-sm)',
        'control-md': 'var(--semantic-control-height-md)',
        'control-lg': 'var(--semantic-control-height-lg)',
      },
      minHeight: {
        'control-sm': 'var(--semantic-control-height-sm)',
        'control-md': 'var(--semantic-control-height-md)',
        'control-lg': 'var(--semantic-control-height-lg)',
      },
      fontSize: {
        '11': 'var(--primitive-font-size11)',
        '12': 'var(--primitive-font-size12)',
        '13': 'var(--primitive-font-size13)',
        '14': 'var(--primitive-font-size14)',
        '16': ['var(--primitive-font-size16)', { lineHeight: 'var(--semantic-font-lineHeight16)' }],
        '18': ['var(--primitive-font-size18)', { lineHeight: 'var(--semantic-font-lineHeight18)' }],
        '24': ['var(--primitive-font-size24)', { lineHeight: 'var(--semantic-font-lineHeight24)' }],
        '32': ['var(--primitive-font-size32)', { lineHeight: 'var(--semantic-font-lineHeight32)' }],
        '40': 'var(--primitive-font-size40)',
        'control-sm': ['var(--semantic-control-font-size-sm)', { lineHeight: 'var(--semantic-control-font-lineHeight)' }],
        'control-md': ['var(--semantic-control-font-size-md)', { lineHeight: 'var(--semantic-control-font-lineHeight)' }],
        'control-lg': ['var(--semantic-control-font-size-lg)', { lineHeight: 'var(--semantic-control-font-lineHeight)' }],
      },
      lineHeight: {
        '16': 'var(--semantic-font-lineHeight16)',
        '18': 'var(--semantic-font-lineHeight18)',
        '20': 'var(--semantic-font-lineHeight20)',
        '24': 'var(--semantic-font-lineHeight24)',
        '28': 'var(--semantic-font-lineHeight28)',
        '32': 'var(--semantic-font-lineHeight32)',
        '36': 'var(--semantic-font-lineHeight36)',
        '48': 'var(--semantic-font-lineHeight48)',
        tight: 'var(--semantic-font-lineHeightTight)',
        normal: 'var(--semantic-font-lineHeightNormal)',
        relaxed: 'var(--semantic-font-lineHeightRelaxed)',
      },
      fontWeight: {
        thin: 'var(--semantic-font-weightThin)',
        extralight: 'var(--semantic-font-weightExtralight)',
        light: 'var(--semantic-font-weightLight)',
        normal: 'var(--semantic-font-weightNormal)',
        medium: 'var(--semantic-font-weightMedium)',
        semibold: 'var(--semantic-font-weightSemibold)',
        bold: 'var(--semantic-font-weightBold)',
        extrabold: 'var(--semantic-font-weightExtrabold)',
        regular: 'var(--semantic-font-weightRegular)',
      },
      fontFamily: {
        sans: 'var(--semantic-font-family)',
        mono: 'var(--semantic-font-familyMono)',
      },
      transitionDuration: {
        fast: 'var(--semantic-transition-fast)',
        normal: 'var(--semantic-transition-normal)',
        slow: 'var(--semantic-transition-slow)',
        interactive: 'var(--semantic-transition-interactive)',
        content: 'var(--semantic-transition-content)',
      },
      transitionTimingFunction: {
        'ease-out': 'var(--semantic-transition-easeOut)',
        'ease-in-out': 'var(--semantic-transition-easeInOut)',
      },
      zIndex: {
        base: 'var(--semantic-zIndex-base)',
        raised: 'var(--semantic-zIndex-raised)',
        dropdown: 'var(--semantic-zIndex-dropdown)',
        modal: 'var(--semantic-zIndex-modal)',
        tooltip: 'var(--semantic-zIndex-tooltip)',
      },
      padding: {
        'control-x-sm': 'var(--semantic-control-padding-x-sm)',
        'control-x-md': 'var(--semantic-control-padding-x-md)',
        'control-x-lg': 'var(--semantic-control-padding-x-lg)',
        'control-y-sm': 'var(--semantic-control-padding-y-sm)',
        'control-y-md': 'var(--semantic-control-padding-y-md)',
        'control-y-lg': 'var(--semantic-control-padding-y-lg)',
      },
      opacity: {
        disabled: 'var(--semantic-opacity-disabled)',
        muted: 'var(--semantic-opacity-muted)',
        hover: 'var(--semantic-opacity-hover)',
        overlay: 'var(--semantic-opacity-overlay)',
      },
    },
  },
  plugins: [],
};
