import { Meta, StoryObj } from '@storybook/react';
import { Password } from './Password';
declare const meta: Meta<typeof Password>;
export default meta;
type Story = StoryObj<typeof Password>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const Required: Story;
export declare const WithHelperText: Story;
export declare const Sizes: Story;
export declare const Disabled: Story;
export declare const ReadOnly: Story;
export declare const Error: Story;
export declare const ErrorBoolean: Story;
export declare const WithoutToggle: Story;
export declare const CustomToggleLabels: Story;
export declare const FullWidth: Story;
export declare const Controlled: Story;
export declare const FormExample: Story;
