import { Meta, StoryObj } from '@storybook/react-vite';
import { Table } from './Table';
declare const meta: Meta<typeof Table>;
export default meta;
type Story = StoryObj<typeof Table>;
export declare const Default: Story;
export declare const WithCustomRendering: Story;
export declare const Selectable: Story;
export declare const Sortable: Story;
export declare const WithActions: Story;
export declare const RowClickable: Story;
export declare const Empty: Story;
export declare const Scrollable: Story;
export declare const ColumnAlignment: Story;
export declare const Resizable: Story;
export declare const ResizableWithSelection: Story;
export declare const ComplexExample: Story;
export declare const HideSelectAll: Story;
export declare const CustomRowHeight: Story;
export declare const ExpandedContent: Story;
export declare const ResizeModeOnChange: Story;
export declare const MinColumnWidth: Story;
