export type InstanceStatus = 'running' | 'stopped' | 'pending' | 'error' | 'building';

export interface Instance {
  id: string;
  name: string;
  status: InstanceStatus;
  locked: boolean;
  fixedIp: string;
  floatingIp: string;
  os: string;
  flavor: string;
  vcpu: number;
  ram: string;
  disk: string;
  gpu: string;
  az: string;
  description?: string;
  [key: string]: unknown;
}

export interface BareMetalInstance {
  id: string;
  name: string;
  status: InstanceStatus;
  locked: boolean;
  os: string;
  flavor: string;
  cpu: number;
  ram: string;
  disk: string;
  gpu: string;
  az: string;
  [key: string]: unknown;
}

export const mockInstances: Instance[] = [
  {
    id: 'vm-001',
    name: 'worker-node-01',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.40',
    floatingIp: '20.30.40.50',
    os: 'Ubuntu 24.04',
    flavor: 'Medium',
    vcpu: 4,
    ram: '8GB',
    disk: '100GB',
    gpu: '1',
    az: 'keystone',
  },
  {
    id: 'vm-002',
    name: 'worker-node-02',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.41',
    floatingIp: '20.30.40.51',
    os: 'CentOS 7',
    flavor: 'Medium',
    vcpu: 4,
    ram: '8GB',
    disk: '100GB',
    gpu: '1',
    az: 'keystone',
  },
  {
    id: 'vm-003',
    name: 'master-node-01',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.10',
    floatingIp: '20.30.40.10',
    os: 'Ubuntu 22.04',
    flavor: 'Large',
    vcpu: 8,
    ram: '16GB',
    disk: '200GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-004',
    name: 'db-server-01',
    status: 'stopped',
    locked: true,
    fixedIp: '10.20.30.20',
    floatingIp: '-',
    os: 'CentOS 8',
    flavor: 'XLarge',
    vcpu: 16,
    ram: '64GB',
    disk: '500GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-005',
    name: 'gpu-node-01',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.50',
    floatingIp: '20.30.40.60',
    os: 'Ubuntu 22.04',
    flavor: 'GPU Large',
    vcpu: 32,
    ram: '128GB',
    disk: '1TB',
    gpu: '4',
    az: 'nova',
  },
  {
    id: 'vm-006',
    name: 'gpu-node-02',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.51',
    floatingIp: '20.30.40.61',
    os: 'Ubuntu 22.04',
    flavor: 'GPU Large',
    vcpu: 32,
    ram: '128GB',
    disk: '1TB',
    gpu: '4',
    az: 'nova',
  },
  {
    id: 'vm-007',
    name: 'web-server-01',
    status: 'pending',
    locked: false,
    fixedIp: '-',
    floatingIp: '-',
    os: 'Rocky Linux 9',
    flavor: 'Small',
    vcpu: 2,
    ram: '4GB',
    disk: '50GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-008',
    name: 'web-server-02',
    status: 'building',
    locked: false,
    fixedIp: '-',
    floatingIp: '-',
    os: 'Rocky Linux 9',
    flavor: 'Small',
    vcpu: 2,
    ram: '4GB',
    disk: '50GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-009',
    name: 'analytics-01',
    status: 'error',
    locked: true,
    fixedIp: '10.20.30.80',
    floatingIp: '-',
    os: 'Debian 12',
    flavor: 'XLarge',
    vcpu: 16,
    ram: '32GB',
    disk: '500GB',
    gpu: '2',
    az: 'nova',
  },
  {
    id: 'vm-010',
    name: 'cache-server-01',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.90',
    floatingIp: '20.30.40.90',
    os: 'Debian 12',
    flavor: 'Medium',
    vcpu: 4,
    ram: '16GB',
    disk: '100GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-011',
    name: 'api-gateway-01',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.100',
    floatingIp: '20.30.40.100',
    os: 'Ubuntu 22.04',
    flavor: 'Medium',
    vcpu: 4,
    ram: '8GB',
    disk: '100GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-012',
    name: 'api-gateway-02',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.101',
    floatingIp: '20.30.40.101',
    os: 'Ubuntu 22.04',
    flavor: 'Medium',
    vcpu: 4,
    ram: '8GB',
    disk: '100GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-013',
    name: 'monitoring-01',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.110',
    floatingIp: '-',
    os: 'CentOS 8',
    flavor: 'Large',
    vcpu: 8,
    ram: '32GB',
    disk: '500GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-014',
    name: 'logging-server-01',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.120',
    floatingIp: '-',
    os: 'Debian 12',
    flavor: 'XLarge',
    vcpu: 16,
    ram: '64GB',
    disk: '2TB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-015',
    name: 'jenkins-master',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.130',
    floatingIp: '20.30.40.130',
    os: 'Ubuntu 22.04',
    flavor: 'Large',
    vcpu: 8,
    ram: '16GB',
    disk: '200GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-016',
    name: 'jenkins-agent-01',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.131',
    floatingIp: '-',
    os: 'Ubuntu 22.04',
    flavor: 'Medium',
    vcpu: 4,
    ram: '8GB',
    disk: '100GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-017',
    name: 'jenkins-agent-02',
    status: 'stopped',
    locked: false,
    fixedIp: '10.20.30.132',
    floatingIp: '-',
    os: 'Ubuntu 22.04',
    flavor: 'Medium',
    vcpu: 4,
    ram: '8GB',
    disk: '100GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-018',
    name: 'gitlab-server',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.140',
    floatingIp: '20.30.40.140',
    os: 'CentOS 8',
    flavor: 'XLarge',
    vcpu: 16,
    ram: '32GB',
    disk: '1TB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-019',
    name: 'nexus-repo',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.150',
    floatingIp: '-',
    os: 'Rocky Linux 9',
    flavor: 'Large',
    vcpu: 8,
    ram: '16GB',
    disk: '500GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-020',
    name: 'redis-cluster-01',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.160',
    floatingIp: '-',
    os: 'Debian 12',
    flavor: 'Medium',
    vcpu: 4,
    ram: '16GB',
    disk: '50GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-021',
    name: 'redis-cluster-02',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.161',
    floatingIp: '-',
    os: 'Debian 12',
    flavor: 'Medium',
    vcpu: 4,
    ram: '16GB',
    disk: '50GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-022',
    name: 'redis-cluster-03',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.162',
    floatingIp: '-',
    os: 'Debian 12',
    flavor: 'Medium',
    vcpu: 4,
    ram: '16GB',
    disk: '50GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-023',
    name: 'kafka-broker-01',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.170',
    floatingIp: '-',
    os: 'Ubuntu 22.04',
    flavor: 'Large',
    vcpu: 8,
    ram: '32GB',
    disk: '500GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-024',
    name: 'kafka-broker-02',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.171',
    floatingIp: '-',
    os: 'Ubuntu 22.04',
    flavor: 'Large',
    vcpu: 8,
    ram: '32GB',
    disk: '500GB',
    gpu: '-',
    az: 'nova',
  },
  {
    id: 'vm-025',
    name: 'kafka-broker-03',
    status: 'error',
    locked: true,
    fixedIp: '10.20.30.172',
    floatingIp: '-',
    os: 'Ubuntu 22.04',
    flavor: 'Large',
    vcpu: 8,
    ram: '32GB',
    disk: '500GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-026',
    name: 'ml-training-01',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.180',
    floatingIp: '20.30.40.180',
    os: 'Ubuntu 22.04',
    flavor: 'GPU XLarge',
    vcpu: 64,
    ram: '256GB',
    disk: '2TB',
    gpu: '8',
    az: 'nova',
  },
  {
    id: 'vm-027',
    name: 'ml-inference-01',
    status: 'running',
    locked: false,
    fixedIp: '10.20.30.181',
    floatingIp: '20.30.40.181',
    os: 'Ubuntu 22.04',
    flavor: 'GPU Large',
    vcpu: 32,
    ram: '128GB',
    disk: '1TB',
    gpu: '4',
    az: 'nova',
  },
  {
    id: 'vm-028',
    name: 'bastion-host',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.190',
    floatingIp: '20.30.40.190',
    os: 'Rocky Linux 9',
    flavor: 'Small',
    vcpu: 2,
    ram: '4GB',
    disk: '50GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-029',
    name: 'vpn-server',
    status: 'running',
    locked: true,
    fixedIp: '10.20.30.200',
    floatingIp: '20.30.40.200',
    os: 'CentOS 8',
    flavor: 'Small',
    vcpu: 2,
    ram: '4GB',
    disk: '50GB',
    gpu: '-',
    az: 'keystone',
  },
  {
    id: 'vm-030',
    name: 'test-instance-01',
    status: 'pending',
    locked: false,
    fixedIp: '-',
    floatingIp: '-',
    os: 'Ubuntu 22.04',
    flavor: 'Small',
    vcpu: 2,
    ram: '4GB',
    disk: '50GB',
    gpu: '-',
    az: 'nova',
  },
];

export const mockBareMetalInstances: BareMetalInstance[] = [
  {
    id: 'bm-001',
    name: 'web-server-1',
    status: 'running',
    locked: false,
    os: 'Ubuntu 22.04',
    flavor: 'BM flavor',
    cpu: 8,
    ram: '16GiB',
    disk: '10GiB',
    gpu: '-',
    az: 'zone-a',
  },
  {
    id: 'bm-002',
    name: 'web-server-2',
    status: 'running',
    locked: false,
    os: 'Ubuntu 22.04',
    flavor: 'BM flavor',
    cpu: 8,
    ram: '16GiB',
    disk: '10GiB',
    gpu: '-',
    az: 'zone-a',
  },
  {
    id: 'bm-003',
    name: 'db-server-1',
    status: 'running',
    locked: true,
    os: 'Rocky Linux 9',
    flavor: 'BM large',
    cpu: 16,
    ram: '64GiB',
    disk: '500GiB',
    gpu: '-',
    az: 'zone-b',
  },
  {
    id: 'bm-004',
    name: 'db-server-2',
    status: 'stopped',
    locked: true,
    os: 'Rocky Linux 9',
    flavor: 'BM large',
    cpu: 16,
    ram: '64GiB',
    disk: '500GiB',
    gpu: '-',
    az: 'zone-b',
  },
  {
    id: 'bm-005',
    name: 'gpu-node-1',
    status: 'running',
    locked: false,
    os: 'Ubuntu 22.04',
    flavor: 'BM GPU',
    cpu: 32,
    ram: '128GiB',
    disk: '1TiB',
    gpu: 'A100 x4',
    az: 'zone-c',
  },
  {
    id: 'bm-006',
    name: 'gpu-node-2',
    status: 'running',
    locked: false,
    os: 'Ubuntu 22.04',
    flavor: 'BM GPU',
    cpu: 32,
    ram: '128GiB',
    disk: '1TiB',
    gpu: 'A100 x4',
    az: 'zone-c',
  },
  {
    id: 'bm-007',
    name: 'compute-1',
    status: 'pending',
    locked: false,
    os: 'CentOS 8',
    flavor: 'BM xlarge',
    cpu: 64,
    ram: '256GiB',
    disk: '2TiB',
    gpu: '-',
    az: 'zone-a',
  },
  {
    id: 'bm-008',
    name: 'compute-2',
    status: 'building',
    locked: false,
    os: 'CentOS 8',
    flavor: 'BM xlarge',
    cpu: 64,
    ram: '256GiB',
    disk: '2TiB',
    gpu: '-',
    az: 'zone-a',
  },
  {
    id: 'bm-009',
    name: 'storage-node-1',
    status: 'running',
    locked: true,
    os: 'Debian 12',
    flavor: 'BM storage',
    cpu: 8,
    ram: '32GiB',
    disk: '10TiB',
    gpu: '-',
    az: 'zone-b',
  },
  {
    id: 'bm-010',
    name: 'storage-node-2',
    status: 'error',
    locked: true,
    os: 'Debian 12',
    flavor: 'BM storage',
    cpu: 8,
    ram: '32GiB',
    disk: '10TiB',
    gpu: '-',
    az: 'zone-b',
  },
];
