import { Meta, StoryObj } from '@storybook/react-vite';
import { FilterSearchInput } from './FilterSearchInput';
declare const meta: Meta<typeof FilterSearchInput>;
export default meta;
type Story = StoryObj<typeof FilterSearchInput>;
export declare const Default: Story;
export declare const WithFilters: Story;
export declare const WithAppliedFilters: Story;
export declare const Sizes: Story;
export declare const HiddenAppliedFilters: Story;
export declare const Disabled: Story;
export declare const SimpleSearch: Story;
