import { Meta, StoryObj } from '@storybook/react-vite';
import { Input } from './Input';
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const Required: Story;
export declare const WithHelperText: Story;
export declare const WithError: Story;
export declare const Sizes: Story;
export declare const Variants: Story;
export declare const WithLeftIcon: Story;
export declare const WithRightIcon: Story;
export declare const WithBothIcons: Story;
export declare const PasswordToggle: Story;
export declare const Disabled: Story;
export declare const ReadOnly: Story;
export declare const FullWidth: Story;
export declare const FormExample: Story;
export declare const AllStates: Story;
