import { Meta, StoryObj } from '@storybook/react-vite';
import { NumberInput } from './NumberInput';
declare const meta: Meta<typeof NumberInput>;
export default meta;
type Story = StoryObj<typeof NumberInput>;
export declare const Default: Story;
export declare const Controlled: Story;
export declare const WithMinMax: Story;
export declare const WithStep: Story;
export declare const WidthVariants: Story;
export declare const HideSteppers: Story;
export declare const WithError: Story;
export declare const WithLabel: Story;
export declare const Disabled: Story;
export declare const AllStates: Story;
