import { Meta, StoryObj } from '@storybook/react-vite';
import { Textarea } from './Textarea';
declare const meta: Meta<typeof Textarea>;
export default meta;
type Story = StoryObj<typeof Textarea>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const Required: Story;
export declare const WithHelperText: Story;
export declare const WithCharacterCount: Story;
export declare const WithError: Story;
export declare const CodeVariant: Story;
export declare const AutoResize: Story;
export declare const ResizeOptions: Story;
export declare const Disabled: Story;
export declare const ReadOnly: Story;
export declare const AllStates: Story;
