import { Meta, StoryObj } from '@storybook/react-vite';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Outline: Story;
export declare const Ghost: Story;
export declare const Muted: Story;
export declare const Danger: Story;
export declare const Warning: Story;
export declare const Link: Story;
export declare const Sizes: Story;
export declare const AllVariants: Story;
export declare const WithLeftIcon: Story;
export declare const WithRightIcon: Story;
export declare const WithBothIcons: Story;
export declare const IconOnly: Story;
export declare const IconOnlyVariants: Story;
export declare const Loading: Story;
export declare const Disabled: Story;
export declare const DisabledVariants: Story;
export declare const FullWidth: Story;
export declare const AsLink: Story;
export declare const Interactive: Story;
