// Auto-generated from tokens/light.json - DO NOT EDIT

/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        primary: 'var(--semantic-color-primary)',
        'primary-hover': 'var(--semantic-color-primaryHover)',
        'primary-focus': 'var(--semantic-color-primaryFocus)',
        'on-primary': 'var(--semantic-color-onPrimary)',
        secondary: 'var(--semantic-color-secondary)',
        'secondary-hover': 'var(--semantic-color-secondaryHover)',
        'secondary-focus': 'var(--semantic-color-secondaryFocus)',
        'on-secondary': 'var(--semantic-color-onSecondary)',
        tertiary: 'var(--semantic-color-tertiary)',
        'tertiary-hover': 'var(--semantic-color-tertiaryHover)',
        'tertiary-focus': 'var(--semantic-color-tertiaryFocus)',
        'on-tertiary': 'var(--semantic-color-onTertiary)',
        surface: 'var(--semantic-color-surface)',
        'surface-muted': 'var(--semantic-color-surfaceMuted)',
        'surface-hover': 'var(--semantic-color-surfaceHover)',
        'surface-tertiary': 'var(--semantic-color-surfaceTertiary)',
        'surface-elevated': 'var(--semantic-color-surfaceElevated)',
        text: 'var(--semantic-color-text)',
        'text-muted': 'var(--semantic-color-textMuted)',
        'text-subtle': 'var(--semantic-color-textSubtle)',
        'text-light': 'var(--semantic-color-textLight)',
        'text-inverse': 'var(--semantic-color-textInverse)',
        success: 'var(--semantic-color-success)',
        'success-light': 'var(--semantic-color-successLight)',
        'on-success': 'var(--semantic-color-onSuccess)',
        error: 'var(--semantic-color-error)',
        'error-light': 'var(--semantic-color-errorLight)',
        'on-error': 'var(--semantic-color-onError)',
        warning: 'var(--semantic-color-warning)',
        'warning-light': 'var(--semantic-color-warningLight)',
        'on-warning': 'var(--semantic-color-onWarning)',
        info: 'var(--semantic-color-info)',
        'info-light': 'var(--semantic-color-infoLight)',
        'on-info': 'var(--semantic-color-onInfo)',
        muted: 'var(--semantic-color-muted)',
        'muted-light': 'var(--semantic-color-mutedLight)',
        'on-muted': 'var(--semantic-color-onMuted)',
        border: 'var(--semantic-color-border)',
        'border-muted': 'var(--semantic-color-borderMuted)',
        'border-subtle': 'var(--semantic-color-borderSubtle)',
        'border-strong': 'var(--semantic-color-borderStrong)',
        focus: 'var(--semantic-color-focus)',
        subtle: 'var(--semantic-color-subtle)',
        'info-weak-bg': 'var(--semantic-color-infoWeakBg)',
        danger: 'var(--semantic-color-danger)',
        'success-bg': 'var(--semantic-color-successBg)',
        'success-strong-bg': 'var(--semantic-color-successStrongBg)',
        'danger-bg': 'var(--semantic-color-dangerBg)',
        'surface-subtle': 'var(--semantic-color-surfaceSubtle)',
        primitive: {
          white: 'var(--primitive-color-white)',
          black: 'var(--primitive-color-black)',
          transparent: 'var(--primitive-color-transparent)',
          blueGray: {
            '10': 'var(--primitive-color-blueGray10)',
            '50': 'var(--primitive-color-blueGray50)',
            '100': 'var(--primitive-color-blueGray100)',
            '150': 'var(--primitive-color-blueGray150)',
            '200': 'var(--primitive-color-blueGray200)',
            '300': 'var(--primitive-color-blueGray300)',
            '400': 'var(--primitive-color-blueGray400)',
            '500': 'var(--primitive-color-blueGray500)',
            '600': 'var(--primitive-color-blueGray600)',
            '700': 'var(--primitive-color-blueGray700)',
            '800': 'var(--primitive-color-blueGray800)',
            '900': 'var(--primitive-color-blueGray900)',
            '950': 'var(--primitive-color-blueGray950)',
          },
          coolGray: {
            '50': 'var(--primitive-color-coolGray50)',
            '100': 'var(--primitive-color-coolGray100)',
            '200': 'var(--primitive-color-coolGray200)',
            '300': 'var(--primitive-color-coolGray300)',
            '400': 'var(--primitive-color-coolGray400)',
            '500': 'var(--primitive-color-coolGray500)',
            '600': 'var(--primitive-color-coolGray600)',
            '700': 'var(--primitive-color-coolGray700)',
            '800': 'var(--primitive-color-coolGray800)',
            '900': 'var(--primitive-color-coolGray900)',
          },
          trueGray: {
            '10': 'var(--primitive-color-trueGray10)',
            '50': 'var(--primitive-color-trueGray50)',
            '100': 'var(--primitive-color-trueGray100)',
            '200': 'var(--primitive-color-trueGray200)',
            '300': 'var(--primitive-color-trueGray300)',
            '400': 'var(--primitive-color-trueGray400)',
            '500': 'var(--primitive-color-trueGray500)',
            '600': 'var(--primitive-color-trueGray600)',
            '700': 'var(--primitive-color-trueGray700)',
            '800': 'var(--primitive-color-trueGray800)',
            '900': 'var(--primitive-color-trueGray900)',
            '950': 'var(--primitive-color-trueGray950)',
          },
          warmGray: {
            '50': 'var(--primitive-color-warmGray50)',
            '100': 'var(--primitive-color-warmGray100)',
            '200': 'var(--primitive-color-warmGray200)',
            '300': 'var(--primitive-color-warmGray300)',
            '400': 'var(--primitive-color-warmGray400)',
            '500': 'var(--primitive-color-warmGray500)',
            '600': 'var(--primitive-color-warmGray600)',
            '700': 'var(--primitive-color-warmGray700)',
            '800': 'var(--primitive-color-warmGray800)',
            '900': 'var(--primitive-color-warmGray900)',
          },
          gray: {
            '50': 'var(--primitive-color-gray50)',
            '100': 'var(--primitive-color-gray100)',
            '200': 'var(--primitive-color-gray200)',
            '300': 'var(--primitive-color-gray300)',
            '400': 'var(--primitive-color-gray400)',
            '500': 'var(--primitive-color-gray500)',
            '600': 'var(--primitive-color-gray600)',
            '700': 'var(--primitive-color-gray700)',
            '800': 'var(--primitive-color-gray800)',
            '900': 'var(--primitive-color-gray900)',
            '950': 'var(--primitive-color-gray950)',
          },
          blue: {
            '10': 'var(--primitive-color-blue10)',
            '50': 'var(--primitive-color-blue50)',
            '100': 'var(--primitive-color-blue100)',
            '200': 'var(--primitive-color-blue200)',
            '300': 'var(--primitive-color-blue300)',
            '400': 'var(--primitive-color-blue400)',
            '500': 'var(--primitive-color-blue500)',
            '600': 'var(--primitive-color-blue600)',
            '700': 'var(--primitive-color-blue700)',
            '800': 'var(--primitive-color-blue800)',
            '900': 'var(--primitive-color-blue900)',
            '950': 'var(--primitive-color-blue950)',
          },
          sky: {
            '50': 'var(--primitive-color-sky50)',
            '100': 'var(--primitive-color-sky100)',
            '200': 'var(--primitive-color-sky200)',
            '300': 'var(--primitive-color-sky300)',
            '400': 'var(--primitive-color-sky400)',
            '500': 'var(--primitive-color-sky500)',
            '600': 'var(--primitive-color-sky600)',
            '700': 'var(--primitive-color-sky700)',
            '800': 'var(--primitive-color-sky800)',
            '900': 'var(--primitive-color-sky900)',
          },
          indigo: {
            '50': 'var(--primitive-color-indigo50)',
            '100': 'var(--primitive-color-indigo100)',
            '200': 'var(--primitive-color-indigo200)',
            '300': 'var(--primitive-color-indigo300)',
            '400': 'var(--primitive-color-indigo400)',
            '500': 'var(--primitive-color-indigo500)',
            '600': 'var(--primitive-color-indigo600)',
            '700': 'var(--primitive-color-indigo700)',
            '800': 'var(--primitive-color-indigo800)',
            '900': 'var(--primitive-color-indigo900)',
          },
          green: {
            '10': 'var(--primitive-color-green10)',
            '50': 'var(--primitive-color-green50)',
            '100': 'var(--primitive-color-green100)',
            '200': 'var(--primitive-color-green200)',
            '300': 'var(--primitive-color-green300)',
            '400': 'var(--primitive-color-green400)',
            '500': 'var(--primitive-color-green500)',
            '600': 'var(--primitive-color-green600)',
            '700': 'var(--primitive-color-green700)',
            '800': 'var(--primitive-color-green800)',
            '900': 'var(--primitive-color-green900)',
            '950': 'var(--primitive-color-green950)',
          },
          emerald: {
            '50': 'var(--primitive-color-emerald50)',
            '100': 'var(--primitive-color-emerald100)',
            '200': 'var(--primitive-color-emerald200)',
            '300': 'var(--primitive-color-emerald300)',
            '400': 'var(--primitive-color-emerald400)',
            '500': 'var(--primitive-color-emerald500)',
            '600': 'var(--primitive-color-emerald600)',
            '700': 'var(--primitive-color-emerald700)',
            '800': 'var(--primitive-color-emerald800)',
            '900': 'var(--primitive-color-emerald900)',
          },
          teal: {
            '50': 'var(--primitive-color-teal50)',
            '100': 'var(--primitive-color-teal100)',
            '200': 'var(--primitive-color-teal200)',
            '300': 'var(--primitive-color-teal300)',
            '400': 'var(--primitive-color-teal400)',
            '500': 'var(--primitive-color-teal500)',
            '600': 'var(--primitive-color-teal600)',
            '700': 'var(--primitive-color-teal700)',
            '800': 'var(--primitive-color-teal800)',
            '900': 'var(--primitive-color-teal900)',
          },
          red: {
            '10': 'var(--primitive-color-red10)',
            '50': 'var(--primitive-color-red50)',
            '100': 'var(--primitive-color-red100)',
            '200': 'var(--primitive-color-red200)',
            '300': 'var(--primitive-color-red300)',
            '400': 'var(--primitive-color-red400)',
            '500': 'var(--primitive-color-red500)',
            '600': 'var(--primitive-color-red600)',
            '700': 'var(--primitive-color-red700)',
            '800': 'var(--primitive-color-red800)',
            '900': 'var(--primitive-color-red900)',
            '950': 'var(--primitive-color-red950)',
          },
          orange: {
            '50': 'var(--primitive-color-orange50)',
            '100': 'var(--primitive-color-orange100)',
            '200': 'var(--primitive-color-orange200)',
            '300': 'var(--primitive-color-orange300)',
            '400': 'var(--primitive-color-orange400)',
            '500': 'var(--primitive-color-orange500)',
            '600': 'var(--primitive-color-orange600)',
            '700': 'var(--primitive-color-orange700)',
            '800': 'var(--primitive-color-orange800)',
            '900': 'var(--primitive-color-orange900)',
          },
          amber: {
            '50': 'var(--primitive-color-amber50)',
            '100': 'var(--primitive-color-amber100)',
            '200': 'var(--primitive-color-amber200)',
            '300': 'var(--primitive-color-amber300)',
            '400': 'var(--primitive-color-amber400)',
            '500': 'var(--primitive-color-amber500)',
            '600': 'var(--primitive-color-amber600)',
            '700': 'var(--primitive-color-amber700)',
            '800': 'var(--primitive-color-amber800)',
            '900': 'var(--primitive-color-amber900)',
          },
          yellow: {
            '10': 'var(--primitive-color-yellow10)',
            '50': 'var(--primitive-color-yellow50)',
            '100': 'var(--primitive-color-yellow100)',
            '200': 'var(--primitive-color-yellow200)',
            '300': 'var(--primitive-color-yellow300)',
            '400': 'var(--primitive-color-yellow400)',
            '500': 'var(--primitive-color-yellow500)',
            '600': 'var(--primitive-color-yellow600)',
            '700': 'var(--primitive-color-yellow700)',
            '800': 'var(--primitive-color-yellow800)',
            '900': 'var(--primitive-color-yellow900)',
            '950': 'var(--primitive-color-yellow950)',
          },
          purple: {
            '50': 'var(--primitive-color-purple50)',
            '100': 'var(--primitive-color-purple100)',
            '200': 'var(--primitive-color-purple200)',
            '300': 'var(--primitive-color-purple300)',
            '400': 'var(--primitive-color-purple400)',
            '500': 'var(--primitive-color-purple500)',
            '600': 'var(--primitive-color-purple600)',
            '700': 'var(--primitive-color-purple700)',
            '800': 'var(--primitive-color-purple800)',
            '900': 'var(--primitive-color-purple900)',
          },
          violet: {
            '50': 'var(--primitive-color-violet50)',
            '100': 'var(--primitive-color-violet100)',
            '200': 'var(--primitive-color-violet200)',
            '300': 'var(--primitive-color-violet300)',
            '400': 'var(--primitive-color-violet400)',
            '500': 'var(--primitive-color-violet500)',
            '600': 'var(--primitive-color-violet600)',
            '700': 'var(--primitive-color-violet700)',
            '800': 'var(--primitive-color-violet800)',
            '900': 'var(--primitive-color-violet900)',
          },
          fuchsia: {
            '50': 'var(--primitive-color-fuchsia50)',
            '100': 'var(--primitive-color-fuchsia100)',
            '200': 'var(--primitive-color-fuchsia200)',
            '300': 'var(--primitive-color-fuchsia300)',
            '400': 'var(--primitive-color-fuchsia400)',
            '500': 'var(--primitive-color-fuchsia500)',
            '600': 'var(--primitive-color-fuchsia600)',
            '700': 'var(--primitive-color-fuchsia700)',
            '800': 'var(--primitive-color-fuchsia800)',
            '900': 'var(--primitive-color-fuchsia900)',
          },
          pink: {
            '50': 'var(--primitive-color-pink50)',
            '100': 'var(--primitive-color-pink100)',
            '200': 'var(--primitive-color-pink200)',
            '300': 'var(--primitive-color-pink300)',
            '400': 'var(--primitive-color-pink400)',
            '500': 'var(--primitive-color-pink500)',
            '600': 'var(--primitive-color-pink600)',
            '700': 'var(--primitive-color-pink700)',
            '800': 'var(--primitive-color-pink800)',
            '900': 'var(--primitive-color-pink900)',
          },
          rose: {
            '50': 'var(--primitive-color-rose50)',
            '100': 'var(--primitive-color-rose100)',
            '200': 'var(--primitive-color-rose200)',
            '300': 'var(--primitive-color-rose300)',
            '400': 'var(--primitive-color-rose400)',
            '500': 'var(--primitive-color-rose500)',
            '600': 'var(--primitive-color-rose600)',
            '700': 'var(--primitive-color-rose700)',
            '800': 'var(--primitive-color-rose800)',
            '900': 'var(--primitive-color-rose900)',
          },
          slate: {
            '50': 'var(--primitive-color-slate50)',
            '100': 'var(--primitive-color-slate100)',
            '200': 'var(--primitive-color-slate200)',
            '300': 'var(--primitive-color-slate300)',
            '400': 'var(--primitive-color-slate400)',
            '500': 'var(--primitive-color-slate500)',
            '600': 'var(--primitive-color-slate600)',
            '700': 'var(--primitive-color-slate700)',
            '800': 'var(--primitive-color-slate800)',
            '900': 'var(--primitive-color-slate900)',
          },
        },
      },
      spacing: {
        '0': 'var(--primitive-space-0)',
        '1': 'var(--primitive-space-1)',
        '2': 'var(--primitive-space-2)',
        '3': 'var(--primitive-space-3)',
        '4': 'var(--primitive-space-4)',
        '5': 'var(--primitive-space-5)',
        '6': 'var(--primitive-space-6)',
        '7': 'var(--primitive-space-7)',
        '8': 'var(--primitive-space-8)',
        '9': 'var(--primitive-space-9)',
        '10': 'var(--primitive-space-10)',
        '12': 'var(--primitive-space-12)',
        '14': 'var(--primitive-space-14)',
        '16': 'var(--primitive-space-16)',
        '20': 'var(--primitive-space-20)',
        '24': 'var(--primitive-space-24)',
        '32': 'var(--primitive-space-32)',
        '0.5': 'var(--primitive-space-0-5)',
        '1.5': 'var(--primitive-space-1-5)',
        '2.5': 'var(--primitive-space-2-5)',
        xs: 'var(--semantic-space-xs)',
        sm: 'var(--semantic-space-sm)',
        md: 'var(--semantic-space-md)',
        lg: 'var(--semantic-space-lg)',
        xl: 'var(--semantic-space-xl)',
        '2xl': 'var(--semantic-space-2xl)',
        '3xl': 'var(--semantic-space-3xl)',
        inline: 'var(--semantic-space-inline)',
        stack: 'var(--semantic-space-stack)',
        inset: 'var(--semantic-space-inset)',
        section: 'var(--semantic-space-section)',
        block: 'var(--semantic-space-block)',
      },
      borderRadius: {
        none: 'var(--semantic-radius-none)',
        sm: 'var(--semantic-radius-sm)',
        base: 'var(--semantic-radius-base)',
        md: 'var(--semantic-radius-md)',
        lg: 'var(--semantic-radius-lg)',
        xl: 'var(--semantic-radius-xl)',
        full: 'var(--semantic-radius-full)',
        control: 'var(--semantic-radius-control)',
        card: 'var(--semantic-radius-card)',
        modal: 'var(--semantic-radius-modal)',
        base4: 'var(--semantic-radius-base4)',
        base6: 'var(--semantic-radius-base6)',
        base8: 'var(--semantic-radius-base8)',
        base16: 'var(--semantic-radius-base16)',
      },
      boxShadow: {
        none: 'var(--semantic-shadow-none)',
        sm: 'var(--semantic-shadow-sm)',
        base: 'var(--semantic-shadow-base)',
        md: 'var(--semantic-shadow-md)',
        lg: 'var(--semantic-shadow-lg)',
        xl: 'var(--semantic-shadow-xl)',
        card: 'var(--semantic-shadow-card)',
        'card-hover': 'var(--semantic-shadow-cardHover)',
        modal: 'var(--semantic-shadow-modal)',
        dropdown: 'var(--semantic-shadow-dropdown)',
        focus: 'var(--semantic-shadow-focus)',
      },
      fontSize: {
        '11': 'var(--semantic-font-size11)',
        '12': 'var(--semantic-font-size12)',
        '13': 'var(--semantic-font-size13)',
        '14': 'var(--semantic-font-size14)',
        '16': [
          'var(--semantic-font-size16)',
          {
            lineHeight: 'var(--semantic-font-lineHeight16)',
          },
        ],
        '18': [
          'var(--semantic-font-size18)',
          {
            lineHeight: 'var(--semantic-font-lineHeight18)',
          },
        ],
        '24': [
          'var(--semantic-font-size24)',
          {
            lineHeight: 'var(--semantic-font-lineHeight24)',
          },
        ],
        '32': [
          'var(--semantic-font-size32)',
          {
            lineHeight: 'var(--semantic-font-lineHeight32)',
          },
        ],
        '40': 'var(--semantic-font-size40)',
        Xs: 'var(--semantic-font-sizeXs)',
        Sm: 'var(--semantic-font-sizeSm)',
        Md: 'var(--semantic-font-sizeMd)',
        Lg: 'var(--semantic-font-sizeLg)',
        Xl: 'var(--semantic-font-sizeXl)',
        '2xl': 'var(--semantic-font-size2xl)',
        '3xl': 'var(--semantic-font-size3xl)',
        '4xl': 'var(--semantic-font-size4xl)',
        'control-sm': [
          'var(--semantic-control-font-size-sm)',
          {
            lineHeight: 'var(--semantic-control-font-lineHeight)',
          },
        ],
        'control-md': [
          'var(--semantic-control-font-size-md)',
          {
            lineHeight: 'var(--semantic-control-font-lineHeight)',
          },
        ],
        'control-lg': [
          'var(--semantic-control-font-size-lg)',
          {
            lineHeight: 'var(--semantic-control-font-lineHeight)',
          },
        ],
      },
      fontWeight: {
        thin: 'var(--semantic-font-weightThin)',
        extralight: 'var(--semantic-font-weightExtralight)',
        light: 'var(--semantic-font-weightLight)',
        normal: 'var(--semantic-font-weightNormal)',
        medium: 'var(--semantic-font-weightMedium)',
        semibold: 'var(--semantic-font-weightSemibold)',
        bold: 'var(--semantic-font-weightBold)',
        extrabold: 'var(--semantic-font-weightExtrabold)',
        black: 'var(--semantic-font-weightBlack)',
        regular: 'var(--semantic-font-weightRegular)',
      },
      fontFamily: {
        sans: 'var(--semantic-font-family)',
        mono: 'var(--semantic-font-familyMono)',
      },
      lineHeight: {
        '16': 'var(--semantic-font-lineHeight16)',
        '18': 'var(--semantic-font-lineHeight18)',
        '20': 'var(--semantic-font-lineHeight20)',
        '24': 'var(--semantic-font-lineHeight24)',
        '28': 'var(--semantic-font-lineHeight28)',
        '32': 'var(--semantic-font-lineHeight32)',
        '36': 'var(--semantic-font-lineHeight36)',
        '48': 'var(--semantic-font-lineHeight48)',
        tight: 'var(--semantic-font-lineHeightTight)',
        normal: 'var(--semantic-font-lineHeightNormal)',
        relaxed: 'var(--semantic-font-lineHeightRelaxed)',
      },
      transitionDuration: {
        fast: 'var(--semantic-transition-fast)',
        normal: 'var(--semantic-transition-normal)',
        slow: 'var(--semantic-transition-slow)',
        interactive: 'var(--semantic-transition-interactive)',
        content: 'var(--semantic-transition-content)',
      },
      transitionTimingFunction: {
        'ease-out': 'var(--semantic-transition-easeOut)',
        'ease-in-out': 'var(--semantic-transition-easeInOut)',
      },
      zIndex: {
        base: 'var(--semantic-zIndex-base)',
        raised: 'var(--semantic-zIndex-raised)',
        dropdown: 'var(--semantic-zIndex-dropdown)',
        modal: 'var(--semantic-zIndex-modal)',
        tooltip: 'var(--semantic-zIndex-tooltip)',
      },
      height: {
        'control-sm': 'var(--semantic-control-height-sm)',
        'control-md': 'var(--semantic-control-height-md)',
        'control-lg': 'var(--semantic-control-height-lg)',
      },
      minHeight: {
        'control-sm': 'var(--semantic-control-height-sm)',
        'control-md': 'var(--semantic-control-height-md)',
        'control-lg': 'var(--semantic-control-height-lg)',
      },
      borderWidth: {
        DEFAULT: 'var(--semantic-border-width)',
        thick: 'var(--semantic-border-widthThick)',
        none: 'var(--semantic-border-widthNone)',
      },
      padding: {
        'control-x-sm': 'var(--semantic-control-padding-x-sm)',
        'control-x-md': 'var(--semantic-control-padding-x-md)',
        'control-x-lg': 'var(--semantic-control-padding-x-lg)',
        'control-y-sm': 'var(--semantic-control-padding-y-sm)',
        'control-y-md': 'var(--semantic-control-padding-y-md)',
        'control-y-lg': 'var(--semantic-control-padding-y-lg)',
      },
      opacity: {
        disabled: 'var(--semantic-opacity-disabled)',
        muted: 'var(--semantic-opacity-muted)',
        hover: 'var(--semantic-opacity-hover)',
        overlay: 'var(--semantic-opacity-overlay)',
      },
    },
  },
  plugins: [],
};
