import { Meta, StoryObj } from '@storybook/react-vite';
import { Checkbox } from './Checkbox';
declare const meta: Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof Checkbox>;
export declare const Default: Story;
export declare const Checked: Story;
export declare const WithDescription: Story;
export declare const Indeterminate: Story;
export declare const Disabled: Story;
export declare const WithError: Story;
export declare const Controlled: Story;
export declare const SelectAllPattern: Story;
export declare const AllStates: Story;
export declare const GroupExample: Story;
