import { Meta, StoryObj } from '@storybook/react-vite';
import { Badge } from './Badge';
declare const meta: Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof Badge>;
export declare const Default: Story;
export declare const ThemesSolid: Story;
export declare const ThemesSubtle: Story;
export declare const Sizes: Story;
export declare const WithDot: Story;
export declare const WithDotSubtle: Story;
export declare const WithIcons: Story;
export declare const StatusBadges: Story;
export declare const UseCases: Story;
export declare const LegacyVariants: Story;
