import { Meta, StoryObj } from '@storybook/react-vite';
import { BadgeList } from './BadgeList';
declare const meta: Meta<typeof BadgeList>;
export default meta;
type Story = StoryObj<typeof BadgeList>;
export declare const Default: Story;
export declare const AllVisible: Story;
export declare const WithOverflow: Story;
export declare const WithTruncation: Story;
export declare const Themed: Story;
export declare const InTableContext: Story;
