import { Meta, StoryObj } from '@storybook/react-vite';
import { WindowControl } from './WindowControl';
declare const meta: Meta<typeof WindowControl>;
export default meta;
type Story = StoryObj<typeof WindowControl>;
export declare const Minimize: Story;
export declare const Maximize: Story;
export declare const Close: Story;
export declare const Disabled: Story;
export declare const AllControls: Story;
export declare const ControlsGroup: Story;
export declare const PartialControls: Story;
export declare const InHeaderContext: Story;
