import { Meta, StoryObj } from '@storybook/react-vite';
import { MenuItem } from './MenuItem';
declare const meta: Meta<typeof MenuItem>;
export default meta;
type Story = StoryObj<typeof MenuItem>;
export declare const Default: Story;
export declare const Active: Story;
export declare const Disabled: Story;
export declare const WithBadge: Story;
export declare const WithoutIcon: Story;
export declare const AllStates: Story;
export declare const SidebarMenu: Story;
export declare const CompactMenu: Story;
