import { Meta, StoryObj } from '@storybook/react-vite';
import { CardTitle } from './CardTitle';
declare const meta: Meta<typeof CardTitle>;
export default meta;
type Story = StoryObj<typeof CardTitle>;
export declare const Default: Story;
export declare const WithDescription: Story;
export declare const WithStatus: Story;
export declare const WithBadges: Story;
export declare const WithStatusAndBadges: Story;
export declare const WithGauge: Story;
export declare const WithIcon: Story;
export declare const AllStatusColors: Story;
export declare const BadgeVariants: Story;
export declare const ComplexExample: Story;
export declare const Clickable: Story;
