import { Meta, StoryObj } from '@storybook/react';
import { EmptyState } from './EmptyState';
declare const meta: Meta<typeof EmptyState>;
export default meta;
type Story = StoryObj<typeof EmptyState>;
export declare const Default: Story;
export declare const NoSearchResults: Story;
export declare const Inline: Story;
export declare const WithoutIcon: Story;
export declare const WithoutAction: Story;
