import { Meta, StoryObj } from '@storybook/react-vite';
import { FloatingCard } from './FloatingCard';
declare const meta: Meta<typeof FloatingCard>;
export default meta;
type Story = StoryObj<typeof FloatingCard>;
export declare const Default: Story;
export declare const WithQuota: Story;
export declare const WithInstanceCount: Story;
export declare const AllStatuses: Story;
export declare const ActionEnabled: Story;
export declare const WithCloseButton: Story;
export declare const WritingStatus: Story;
export declare const DisabledAction: Story;
export declare const MultipleSections: Story;
