import { Meta, StoryObj } from '@storybook/react-vite';
import { Select } from './Select';
declare const meta: Meta<typeof Select>;
export default meta;
type Story = StoryObj<typeof Select>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const Required: Story;
export declare const WithHelperText: Story;
export declare const WithError: Story;
export declare const WithDefaultValue: Story;
export declare const Controlled: Story;
export declare const Clearable: Story;
export declare const WithDisabledOptions: Story;
export declare const Sizes: Story;
export declare const Widths: Story;
export declare const FullWidth: Story;
export declare const Disabled: Story;
export declare const FormExample: Story;
export declare const AllStates: Story;
