import { Meta, StoryObj } from '@storybook/react';
import { Tag } from './Tag';
declare const meta: Meta<typeof Tag>;
export default meta;
type Story = StoryObj<typeof Tag>;
export declare const Default: Story;
export declare const Variants: Story;
export declare const OutlineVariants: Story;
export declare const Sizes: Story;
export declare const Rounded: Story;
export declare const WithIcon: Story;
export declare const Closable: Story;
export declare const ClosableVariants: Story;
export declare const Clickable: Story;
export declare const Disabled: Story;
export declare const TagGroupExample: Story;
export declare const SkillTags: Story;
export declare const StatusTags: Story;
export declare const FilterTags: Story;
