/**
 * Notion 콘텐츠 동기화 스크립트
 *
 * Notion API를 통해 매핑된 페이지 콘텐츠를 가져와
 * src/content/notion/ 디렉토리에 JSON 파일로 저장합니다.
 *
 * 사용법: npm run sync-notion
 * 사전 조건: .env에 NOTION_API_TOKEN 설정 필요
 */

import { Client } from '@notionhq/client';
import { NotionToMarkdown } from 'notion-to-md';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CONTENT_DIR = path.resolve(__dirname, '../src/content/notion');

// .env 파일에서 토큰 읽기
function loadEnv() {
  const envPath = path.resolve(__dirname, '../.env');
  if (!fs.existsSync(envPath)) {
    console.error('❌ .env 파일을 찾을 수 없습니다.');
    process.exit(1);
  }
  const content = fs.readFileSync(envPath, 'utf-8');
  const lines = content.split('\n');
  for (const line of lines) {
    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      process.env[key.trim()] = valueParts.join('=').trim();
    }
  }
}

// 매핑 파일에서 매핑 데이터 읽기 (TypeScript 파일을 간단히 파싱)
function loadMapping() {
  const mappingPath = path.resolve(CONTENT_DIR, 'mapping.ts');
  const content = fs.readFileSync(mappingPath, 'utf-8');

  const mapping = {};
  const regex = /['"]([^'"]+)['"]\s*:\s*['"]([^'"]+)['"]/g;
  let match;
  while ((match = regex.exec(content)) !== null) {
    if (match[1] && match[2]) {
      mapping[match[1]] = match[2];
    }
  }
  return mapping;
}

async function syncPage(notion, n2m, slug, pageId) {
  try {
    console.log(`  📄 ${slug} (${pageId.slice(0, 8)}...)...`);

    // 페이지 메타데이터 가져오기
    const page = await notion.pages.retrieve({ page_id: pageId });
    const title =
      page.properties?.['이름']?.title?.[0]?.plain_text ||
      page.properties?.title?.title?.[0]?.plain_text ||
      slug;

    // 마크다운으로 변환
    const mdBlocks = await n2m.pageToMarkdown(pageId);
    const mdString = n2m.toMarkdownString(mdBlocks);
    const markdown = typeof mdString === 'string' ? mdString : mdString.parent || '';

    const result = {
      id: pageId,
      slug,
      title,
      markdown,
      lastSynced: new Date().toISOString(),
      editUrl: `https://www.notion.so/${pageId.replace(/-/g, '')}`,
    };

    const outPath = path.join(CONTENT_DIR, `${slug}.json`);
    fs.writeFileSync(outPath, JSON.stringify(result, null, 2), 'utf-8');
    console.log(`  ✅ ${slug} → ${path.relative(process.cwd(), outPath)}`);
    return true;
  } catch (err) {
    console.error(`  ❌ ${slug} 실패:`, err.message);
    return false;
  }
}

async function main() {
  loadEnv();

  const token = process.env.NOTION_API_TOKEN;
  if (!token) {
    console.error('❌ NOTION_API_TOKEN이 .env에 설정되어 있지 않습니다.');
    console.error('   1. https://www.notion.so/my-integrations 에서 Integration 생성');
    console.error('   2. .env 파일에 NOTION_API_TOKEN=ntn_xxxx 추가');
    console.error('   3. 연동할 Notion 페이지에 Integration 접근 권한 부여');
    process.exit(1);
  }

  const notion = new Client({ auth: token });
  const n2m = new NotionToMarkdown({ notionClient: notion });

  const mapping = loadMapping();
  const slugs = Object.keys(mapping);

  if (slugs.length === 0) {
    console.log('ℹ️  매핑된 페이지가 없습니다. src/content/notion/mapping.ts를 확인하세요.');
    return;
  }

  console.log(`\n🔄 Notion 콘텐츠 동기화 시작 (${slugs.length}개 페이지)\n`);

  let success = 0;
  let failed = 0;

  for (const slug of slugs) {
    const ok = await syncPage(notion, n2m, slug, mapping[slug]);
    if (ok) success++;
    else failed++;
  }

  // 인덱스 파일 생성 (동적 import를 위해)
  const indexContent = `// Auto-generated by sync-notion.mjs — DO NOT EDIT
// Last synced: ${new Date().toISOString()}

${slugs
  .map((slug) => {
    const varName = slug.replace(/-/g, '_');
    return `import ${varName}_data from './${slug}.json';`;
  })
  .join('\n')}

export const notionContent: Record<string, { id: string; slug: string; title: string; markdown: string; lastSynced: string; editUrl: string }> = {
${slugs.map((slug) => `  '${slug}': ${slug.replace(/-/g, '_')}_data,`).join('\n')}
};
`;

  fs.writeFileSync(path.join(CONTENT_DIR, 'index.ts'), indexContent, 'utf-8');

  console.log(`\n✨ 완료: ${success}개 성공, ${failed}개 실패\n`);
}

main().catch((err) => {
  console.error('💥 동기화 실패:', err);
  process.exit(1);
});
