import { Meta, StoryObj } from '@storybook/react-vite';
import { SectionCard } from './SectionCard';
declare const meta: Meta<typeof SectionCard>;
export default meta;
type Story = StoryObj<typeof SectionCard>;
export declare const Default: Story;
export declare const ActiveState: Story;
export declare const WithHeaderActions: Story;
export declare const WithCustomContent: Story;
export declare const WithLink: Story;
export declare const WithDivider: Story;
export declare const HeaderWithDescription: Story;
export declare const HeaderWithStatusIcon: Story;
export declare const ContentWithoutDividers: Story;
export declare const ContentWithCustomGap: Story;
export declare const MultipleCards: Story;
