import { Meta, StoryObj } from '@storybook/react-vite';
declare const meta: Meta;
export default meta;
type Story = StoryObj;
export declare const TextColors: Story;
export declare const SurfaceColors: Story;
export declare const BorderColors: Story;
export declare const StateColors: Story;
export declare const ActionColors: Story;
export declare const AllColors: Story;
