import { Meta, StoryObj } from '@storybook/react-vite';
import { Tooltip } from './Tooltip';
declare const meta: Meta<typeof Tooltip>;
export default meta;
type Story = StoryObj<typeof Tooltip>;
export declare const Default: Story;
export declare const Positions: Story;
export declare const WithIcon: Story;
export declare const OnButton: Story;
export declare const LongContent: Story;
export declare const WithJSXContent: Story;
export declare const Delays: Story;
export declare const Disabled: Story;
export declare const FocusSupport: Story;
export declare const RealWorldExample: Story;
