import { Meta, StoryObj } from '@storybook/react-vite';
import { Modal } from './Modal';
declare const meta: Meta<typeof Modal>;
export default meta;
type Story = StoryObj<typeof Modal>;
export declare const Default: Story;
export declare const Confirm: Story;
export declare const DeleteConfirm: Story;
export declare const WithForm: Story;
export declare const Loading: Story;
export declare const Warning: Story;
export declare const NoBackdropClose: Story;
