import { Meta, StoryObj } from '@storybook/react';
import { Dropdown } from './Dropdown';
declare const meta: Meta<typeof Dropdown.Root>;
export default meta;
type Story = StoryObj<typeof Dropdown.Root>;
export declare const Default: Story;
export declare const WithDefaultValue: Story;
export declare const Controlled: Story;
export declare const WithDisabledOptions: Story;
export declare const Disabled: Story;
export declare const Sizes: Story;
export declare const Widths: Story;
export declare const WithGroups: Story;
export declare const WithDividers: Story;
export declare const ErrorState: Story;
export declare const LongList: Story;
export declare const ThakiUIStyle: Story;
