import { Meta, StoryObj } from '@storybook/react-vite';
import { RadioGroup } from './RadioGroup';
declare const meta: Meta<typeof RadioGroup>;
export default meta;
type Story = StoryObj<typeof RadioGroup>;
export declare const Default: Story;
export declare const WithLabelAndDescription: Story;
export declare const Horizontal: Story;
export declare const Controlled: Story;
export declare const Disabled: Story;
export declare const WithError: Story;
export declare const PlanSelection: Story;
export declare const AllStates: Story;
